sudo: false

language: generic

script:
  - make
  - touch .nojekyll


env:
  global:
    - PANDOC="$HOME/.pandoc"
    - PANDOC_DEB="https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb"

before_install:
  - mkdir -p "$PANDOC"
  - curl -L https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb > "$PANDOC/pandoc.deb"
  - dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"
  - export PATH="$PANDOC/usr/bin:$PATH"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  fqdn: haskell-for-readers.nomeata.de
  on:
    branch: master
