sudo: false

language: haskell

ghc:
  - "8.4"

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-xetex
      - lmodern
      - fonts-freefont-ttf
      - fonts-freefont-otf

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

env:
  global:
    - PANDOC="$HOME/.pandoc"
    - PANDOC_DEB="https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb"

before_install:
  - mkdir -p "$PANDOC"
  - curl -L https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb > "$PANDOC/pandoc.deb"
  - dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"
  - export PATH="$PANDOC/usr/bin:$PATH"

install:
  - cabal install pandoc-types

script:
  - make
  - mkdir out/
  - touch out/nojekyll
  - mv haskell-for-readers.html out/index.html
  - mv *.pdf out/
  - mv code-slides.html out/slides.html
  - mv *.css *.png out/

deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  fqdn: haskell-for-readers.nomeata.de
  on:
    branch: master
